package Vista.frm;

import Clases.AjustesObjetos;
import Clases.Base_De_Datos;
import Clases.ConexionBD;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import javax.swing.JOptionPane;

public class frmLogin extends javax.swing.JFrame {
    
    private Base_De_Datos baseDatos;
    
    public frmLogin(Base_De_Datos dato) {
        initComponents();
        this.baseDatos =dato;
        this.getContentPane().setBackground(new Color(221,205,192));
        setSize(820,365);
        setResizable(false);
        setLocationRelativeTo(null);
        AjustesObjetos.ajustarImagen(lbLogo,"src\\imagenes\\495226120_1231826352323647_5717401017301611521_n.jpg");       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        txtRespuestas = new javax.swing.JLabel();
        btnSecion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("CBN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(530, 20, 77, 44);

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel2.setText("usuario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 140, 103, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel3.setText("contraseña:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 200, 140, 32);

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyPressed(evt);
                txtContraseñaKeyPressed2(evt);
            }
        });
        getContentPane().add(txtContraseña);
        txtContraseña.setBounds(530, 200, 240, 30);

        txtUsuario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
                txtUsuarioKeyPressed2(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(530, 140, 240, 30);
        getContentPane().add(txtRespuestas);
        txtRespuestas.setBounds(737, 108, 143, 0);

        btnSecion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSecion.setText("iniciar secion");
        btnSecion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecionActionPerformed(evt);
            }
        });
        getContentPane().add(btnSecion);
        btnSecion.setBounds(510, 280, 160, 32);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(370, 260, 430, 10);

        lbLogo.setText("jLabel4");
        getContentPane().add(lbLogo);
        lbLogo.setBounds(-20, 0, 370, 330);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Lideres en educacion");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(440, 70, 260, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private List<String> obtenerCargosPermitidos() {
        List<String> cargos = new ArrayList<>();
        String sql = "{CALL Cargos()}";
    
        try {
            Connection conn = ConexionBD.getConnection(); 
            CallableStatement cs = conn.prepareCall(sql);
            ResultSet rs = cs.executeQuery();

            while (rs.next()) {
                cargos.add(rs.getString("cargo"));
            }
            rs.close();
            cs.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar cargos: " + e.getMessage());
        }
    
    
        return new ArrayList<>(new LinkedHashSet<>(cargos));
    }
    
    private void btnSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecionActionPerformed
        // TODO add your handling code here:
        String usuario = txtUsuario.getText().trim();
        String contraseña = new String(txtContraseña.getPassword());

        if (usuario.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String rol = baseDatos.login(usuario, contraseña);

        if (rol == null) {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Acceso denegado", JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        List<String> cargosPermitidos = obtenerCargosPermitidos(); 

        boolean rolValido = false;
        for (String cargo : cargosPermitidos) {
            if (rol.equalsIgnoreCase(cargo)) {
                rolValido = true;
                break;
            }
        }

        if (!rolValido) {
            JOptionPane.showMessageDialog(this, 
                "Su cargo '" + rol + "' no está autorizado para acceder al sistema.\n" +
                "Contacte al administrador si cree que esto es un error.", 
                "Acceso Restringido", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        frmplataforma panel = new frmplataforma(baseDatos, rol, usuario);
        panel.setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_btnSecionActionPerformed
    
   
    private void txtContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSecion.doClick();
        }
    }//GEN-LAST:event_txtContraseñaKeyPressed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSecion.doClick();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtUsuarioKeyPressed2(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed2
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txtContraseña.requestFocus();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed2

    private void txtContraseñaKeyPressed2(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyPressed2
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txtUsuario.requestFocus();
        }
    }//GEN-LAST:event_txtContraseñaKeyPressed2

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSecion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JLabel txtRespuestas;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
