/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import clases.Base_De_Datos;
import javax.swing.Box;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class frmAdministrador extends javax.swing.JFrame {
    private final Base_De_Datos baseDatos;
    private String nombre;
   

    /**
     * Creates new form frmAdministrador
     */
    public frmAdministrador(Base_De_Datos baseDatos,String nombreEstudiante) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.nombre=nombreEstudiante;
        btnnombre.setText("Bienvenido, " + nombreEstudiante);
        this.baseDatos = baseDatos;
        jMenuBar1.add(Box.createHorizontalGlue()); 
        jMenuBar1.add(btnVolver);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnVolver = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnnombre = new javax.swing.JMenu();
        btngestionp = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        btncrearMateria = new javax.swing.JMenuItem();
        btnAsignarMateria = new javax.swing.JMenuItem();
        btnReinicio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setText("cerrar seccion");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(btnVolver, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 410, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(btnVolver)
                .addGap(0, 264, Short.MAX_VALUE))
        );

        btnnombre.setText("File");
        jMenuBar1.add(btnnombre);

        btngestionp.setText("gestionar ");
        btngestionp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem1.setText("estudianes");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btngestionp.add(jMenuItem1);

        jMenuItem3.setText("personal");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btngestionp.add(jMenuItem3);

        jMenu1.setText("Asignaturas");

        btncrearMateria.setText("crear materia");
        btncrearMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearMateriaActionPerformed(evt);
            }
        });
        jMenu1.add(btncrearMateria);

        btnAsignarMateria.setText("asignar materia");
        btnAsignarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarMateriaActionPerformed(evt);
            }
        });
        jMenu1.add(btnAsignarMateria);

        btngestionp.add(jMenu1);

        btnReinicio.setText("reiniciar periodo academico");
        btnReinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReinicioActionPerformed(evt);
            }
        });
        btngestionp.add(btnReinicio);

        jMenuBar1.add(btngestionp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        new frmLogin(baseDatos).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnReinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinicioActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "✅ semestre reiniciado");
        baseDatos.reiniciarNotas();
    }//GEN-LAST:event_btnReinicioActionPerformed

    private void btncrearMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearMateriaActionPerformed
        // TODO add your handling code here:
        JiFrmAsignarMateria Materia2=new JiFrmAsignarMateria(nombre);
        jDesktopPane1.add(Materia2);
        Materia2.show();
    }//GEN-LAST:event_btncrearMateriaActionPerformed

    private void btnAsignarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarMateriaActionPerformed
        // TODO add your handling code here:
        JiFrmNuevaMateria materia=new JiFrmNuevaMateria(nombre);
        jDesktopPane1.add(materia);
        materia.show();
    }//GEN-LAST:event_btnAsignarMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAsignarMateria;
    private javax.swing.JMenuItem btnReinicio;
    private javax.swing.JButton btnVolver;
    private javax.swing.JMenuItem btncrearMateria;
    private javax.swing.JMenu btngestionp;
    private javax.swing.JMenu btnnombre;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables

   
}
