package vista;

import clases.Base_De_Datos;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Locale;
import javax.swing.Box;


public class frmdesarrollador extends javax.swing.JFrame {
        private final Base_De_Datos baseDatos;
        private String Nombre;

   public frmdesarrollador(Base_De_Datos basedato,String nombre){
    this.baseDatos = basedato;
    this.Nombre = nombre;

    initComponents(); 

    
    ajustarImagenBoton();

    
    this.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent e) {
            ajustarImagenBoton();
            jButton1.setSize(jdescritorio.getSize());
        }
    });

    setLocationRelativeTo(null); // Centrar ventana
    this.getContentPane().setBackground(new Color(255, 254, 214));
}

    
    
    private void ajustarImagenBoton() {
    java.awt.Image img = new javax.swing.ImageIcon(getClass().getResource("/vista/hq720.jpg")).getImage();
    java.awt.Image imgEscalada = img.getScaledInstance(jButton1.getWidth(), jButton1.getHeight(), java.awt.Image.SCALE_SMOOTH);
    jButton1.setIcon(new javax.swing.ImageIcon(imgEscalada));
}

    
    
    public void setUsuario(String usuario){
            this.Nombre = usuario;
            jMenu1.setText("Bienvenido profesor " + usuario);
             jMenuBar1.add(Box.createHorizontalGlue()); 
             jMenuBar1.add(btnsalir);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        btnsalir = new javax.swing.JButton();
        jdescritorio = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnDocentes = new javax.swing.JMenu();
        btnDnotas = new javax.swing.JMenuItem();
        btnDlista = new javax.swing.JMenuItem();
        btnDpromedio = new javax.swing.JMenuItem();
        btnAlumno = new javax.swing.JMenu();
        btnAdmin = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        btnsalir.setText("cerrar sesion");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdescritorio.setPreferredSize(new java.awt.Dimension(0, 231));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/hq720.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jdescritorio.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdescritorioLayout = new javax.swing.GroupLayout(jdescritorio);
        jdescritorio.setLayout(jdescritorioLayout);
        jdescritorioLayout.setHorizontalGroup(
            jdescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, Short.MAX_VALUE)
        );
        jdescritorioLayout.setVerticalGroup(
            jdescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdescritorioLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(110, 30));

        jMenu1.setText("Un gusto verlo de nuevo señor");
        jMenuBar1.add(jMenu1);

        btnDocentes.setText("Docente");
        btnDocentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnDnotas.setText("Notas");
        btnDnotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDnotasActionPerformed(evt);
            }
        });
        btnDocentes.add(btnDnotas);

        btnDlista.setText("Listado");
        btnDlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlistaActionPerformed(evt);
            }
        });
        btnDocentes.add(btnDlista);

        btnDpromedio.setText("Promedio del grupo");
        btnDocentes.add(btnDpromedio);

        jMenuBar1.add(btnDocentes);

        btnAlumno.setText("Alumno");
        jMenuBar1.add(btnAlumno);

        btnAdmin.setText("Administrador");
        jMenuBar1.add(btnAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdescritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdescritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        cerrarSesion(); 
    }//GEN-LAST:event_btnsalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDlistaActionPerformed

    private void btnDnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDnotasActionPerformed
        // TODO add your handling code here:
        JiFrmPrueba notas=new JiFrmPrueba(baseDatos, Nombre);
        jdescritorio.add(notas);
        notas.show();
    }//GEN-LAST:event_btnDnotasActionPerformed

  

   

    private void cerrarSesion() {
        this.dispose();
        new frmLogin(baseDatos).setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnAdmin;
    private javax.swing.JMenu btnAlumno;
    private javax.swing.JMenuItem btnDlista;
    private javax.swing.JMenuItem btnDnotas;
    private javax.swing.JMenu btnDocentes;
    private javax.swing.JMenuItem btnDpromedio;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdescritorio;
    // End of variables declaration//GEN-END:variables
}
