package vista;

import clases.Base_De_Datos;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Locale;
import javax.swing.Box;


public class frmdesarrollador extends javax.swing.JFrame {
        private final Base_De_Datos baseDatos;
        private String Nombre;

   public frmdesarrollador(Base_De_Datos basedato,String nombre){
    this.baseDatos = basedato;
    this.Nombre = nombre;

    initComponents(); 

    
    ajustarImagenBoton();

    
    this.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent e) {
            ajustarImagenBoton();
            jButton1.setSize(jdescritorio.getSize());
        }
    });

    setLocationRelativeTo(null); // Centrar ventana
    this.getContentPane().setBackground(new Color(255, 254, 214));
}

    
    
    private void ajustarImagenBoton() {
    java.awt.Image img = new javax.swing.ImageIcon(getClass().getResource("/vista/hq720.jpg")).getImage();
    java.awt.Image imgEscalada = img.getScaledInstance(jButton1.getWidth(), jButton1.getHeight(), java.awt.Image.SCALE_SMOOTH);
    jButton1.setIcon(new javax.swing.ImageIcon(imgEscalada));
}

    
    
    public void setUsuario(String usuario){
            this.Nombre = usuario;
            jMenu1.setText("Bienvenido profesor " + usuario);
             jMenuBar1.add(Box.createHorizontalGlue()); 
             jMenuBar1.add(btnsalir);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        btnsalir = new javax.swing.JButton();
        jdescritorio = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnAsignarnotas = new javax.swing.JMenu();
        btnNotas = new javax.swing.JMenuItem();
        btnListaEstudiantes = new javax.swing.JMenuItem();
        btnPromedio = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        btnsalir.setText("cerrar sesion");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdescritorio.setPreferredSize(new java.awt.Dimension(0, 231));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/hq720.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jdescritorio.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdescritorioLayout = new javax.swing.GroupLayout(jdescritorio);
        jdescritorio.setLayout(jdescritorioLayout);
        jdescritorioLayout.setHorizontalGroup(
            jdescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, Short.MAX_VALUE)
        );
        jdescritorioLayout.setVerticalGroup(
            jdescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdescritorioLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(110, 30));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        btnAsignarnotas.setText("estudiantes");
        btnAsignarnotas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnNotas.setText("Notas");
        btnNotas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasActionPerformed(evt);
            }
        });
        btnAsignarnotas.add(btnNotas);

        btnListaEstudiantes.setText("Listado");
        btnListaEstudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListaEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaEstudiantesActionPerformed(evt);
            }
        });
        btnAsignarnotas.add(btnListaEstudiantes);

        btnPromedio.setText("promedio academico");
        btnPromedio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromedioActionPerformed(evt);
            }
        });
        btnAsignarnotas.add(btnPromedio);

        jMenuBar1.add(btnAsignarnotas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdescritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdescritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasActionPerformed
        // TODO add your handling code here:
        abrirNotas();
    }//GEN-LAST:event_btnNotasActionPerformed

    private void btnListaEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaEstudiantesActionPerformed
        // TODO add your handling code here:
        JiFrmListaestudiantes lista=new JiFrmListaestudiantes(baseDatos, Nombre);
        jdescritorio.add(lista);
        lista.show();
        
    }//GEN-LAST:event_btnListaEstudiantesActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        cerrarSesion(); 
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedioActionPerformed
        // TODO add your handling code here:
        JiFrmPromedioGrupo nota=new JiFrmPromedioGrupo(Nombre);
        jdescritorio.add(nota);
        nota.show();
    }//GEN-LAST:event_btnPromedioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

  

    private void abrirNotas() {
        JiFrmPrueba prueba = new JiFrmPrueba(baseDatos,Nombre);
        jdescritorio.add(prueba);
        prueba.show();
        
    }

    private void cerrarSesion() {
        this.dispose();
        new frmLogin(baseDatos).setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnAsignarnotas;
    private javax.swing.JMenuItem btnListaEstudiantes;
    private javax.swing.JMenuItem btnNotas;
    private javax.swing.JMenuItem btnPromedio;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdescritorio;
    // End of variables declaration//GEN-END:variables
}
