package vista;

import clases.Base_De_Datos;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Locale;


public class frmDocente extends javax.swing.JFrame {
        private final Base_De_Datos baseDatos;
        private String Nombre;

    public frmDocente(Base_De_Datos basedato,String nombre){
        this.baseDatos=basedato;
        this.Nombre=nombre;
        initComponents();
        setLocationRelativeTo(null); // Centrar ventana
        configurarEventos();
        this.getContentPane().setBackground(new Color(255, 254, 214));
    }
    
    public void setUsuario(String usuario){
            this.Nombre = usuario;
            txtnombre.setText("Bienvenido profesor " + usuario);
    }
    
    private void configurarEventos() {
        btnListaEstudiantes.addActionListener(e -> abrirListaEstudiantes());
        btnNotas.addActionListener(e -> abrirNotas());
        btnCerrar.addActionListener(e -> cerrarSesion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListaEstudiantes = new javax.swing.JButton();
        btnNotas = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtnombre = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnListaEstudiantes.setText("Listado de estudiantes");
        btnListaEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaEstudiantesActionPerformed(evt);
            }
        });

        btnNotas.setText("asignacion de notas");
        btnNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasActionPerformed(evt);
            }
        });

        jButton3.setText("reportes de estudiantes");

        txtnombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtnombre.setText("nombre del docente");

        btnCerrar.setText("volver");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListaEstudiantes)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNotas)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtnombre)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListaEstudiantes)
                    .addComponent(btnNotas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btnCerrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasActionPerformed
         
    }//GEN-LAST:event_btnNotasActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnListaEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaEstudiantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaEstudiantesActionPerformed

    private void abrirListaEstudiantes() {
         frmListaEstudiantes lista = new frmListaEstudiantes(baseDatos, Nombre);
         
          int x = this.getX();
          int y = this.getY();
          int ancho = this.getWidth();
          lista.setLocation(x + ancho + 10, y);
          lista.setVisible(true);
          
    }

    private void abrirNotas() {
        this.dispose();
        new frmNotasProfe(baseDatos,Nombre).setVisible(true);
    }

    private void cerrarSesion() {
        this.dispose();
        new frmLogin(baseDatos).setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnListaEstudiantes;
    private javax.swing.JButton btnNotas;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel txtnombre;
    // End of variables declaration//GEN-END:variables
}
