/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.Random;
import clases.Base_De_Datos;
import java.awt.Color;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class frmEstudiante extends javax.swing.JFrame {
    private final Base_De_Datos baseDatos;
    private String usuario="";
    private Random random;

    /**
     * Creates new form frmEstudiante
     */
    public frmEstudiante(Base_De_Datos baseDatos) {
        random = new Random();
        initComponents();
        this.baseDatos = baseDatos;
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(255, 254, 214));
    }


   public void setUsuario(String Usuario) {
    this.usuario = Usuario;  
    jMenuBar1.add(Box.createHorizontalGlue()); 
    jMenuBar1.add(btnVolver);

    String sexo = baseDatos.obtenerSexoAlumno(this.usuario);
    boolean fotoAleatoria = random.nextBoolean();

    if (sexo != null) {
        System.out.println("El alumno es: " + sexo);
    }

    try {
        if ("hombre".equalsIgnoreCase(sexo)) {
            if (fotoAleatoria) {
                jMenu1.setIcon(new ImageIcon(getClass().getResource("/imagenes/hombres/d1e3d2a12bc3d0221898c4391dffcfff.jpg")));
            } else {
                jMenu1.setIcon(new ImageIcon(getClass().getResource("/imagenes/hombres/hombre.jpg")));
            }
        } else if ("mujer".equalsIgnoreCase(sexo)) {
            if (fotoAleatoria) {
                jMenu1.setIcon(new ImageIcon(getClass().getResource("/imagenes/mujeres/mujer (2).jpg")));
            } else {
                jMenu1.setIcon(new ImageIcon(getClass().getResource("/imagenes/mujeres/mujerqwe.jpg")));
            }
        } else {
            System.out.println("⚠ Sexo no reconocido o nulo, se asignará imagen por defecto");
            jMenu1.setIcon(new ImageIcon(getClass().getResource("/imagenes/default.png")));
        }
    } catch (Exception e) {
        System.out.println("❌ No se pudo cargar la imagen: " + e.getMessage());
    }
}



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jdEscritorio = new javax.swing.JDesktopPane();
        btnVolver = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnNota = new javax.swing.JMenu();
        btnNotaas = new javax.swing.JMenuItem();
        btnReportes = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVolver.setText("volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.setMaximumSize(new java.awt.Dimension(100, 40));
        btnVolver.setMinimumSize(new java.awt.Dimension(100, 40));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jdEscritorio.setLayer(btnVolver, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdEscritorioLayout = new javax.swing.GroupLayout(jdEscritorio);
        jdEscritorio.setLayout(jdEscritorioLayout);
        jdEscritorioLayout.setHorizontalGroup(
            jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdEscritorioLayout.createSequentialGroup()
                .addGap(0, 707, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jdEscritorioLayout.setVerticalGroup(
            jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdEscritorioLayout.createSequentialGroup()
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 354, Short.MAX_VALUE))
        );

        jMenuBar1.add(jMenu1);

        btnNota.setText("notas y reportes");
        btnNota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotaActionPerformed(evt);
            }
        });

        btnNotaas.setText("notas");
        btnNotaas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNotaas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotaasActionPerformed(evt);
            }
        });
        btnNota.add(btnNotaas);

        btnReportes.setText("reportes");
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNota.add(btnReportes);

        jMenuBar1.add(btnNota);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        frmLogin login = new frmLogin(baseDatos);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotaActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_btnNotaActionPerformed

    private void btnNotaasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotaasActionPerformed
        // TODO add your handling code here:
        JiFrmNotas NOTAS=new JiFrmNotas(usuario);
        jdEscritorio.add(NOTAS);
        NOTAS.show();
    }//GEN-LAST:event_btnNotaasActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnNota;
    private javax.swing.JMenuItem btnNotaas;
    private javax.swing.JMenuItem btnReportes;
    private javax.swing.JButton btnVolver;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JDesktopPane jdEscritorio;
    // End of variables declaration//GEN-END:variables
}
