/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


import clases.Base_De_Datos;
import clases.ConexionBD;
import java.awt.Color;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author PC
 */
public class frmNotasProfe extends javax.swing.JFrame {
       private final Base_De_Datos baseDatos;
       private final String profesor;

    /**
     * Creates new form NotasProfe
     */
        public frmNotasProfe(Base_De_Datos basedatos, String profesor) {
           initComponents();
          
           this.baseDatos=basedatos;
           this.getContentPane().setBackground(new Color(255, 254, 214));

           txtMateria.setHorizontalAlignment(SwingConstants.CENTER);

    // Opcional: darle estilo de título
    txtMateria.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));

    // Hacemos que el label se expanda en la fila superior sin mover botones
    ((GroupLayout) getContentPane().getLayout())
        .setHorizontalGroup(
            ((GroupLayout) getContentPane().getLayout()).createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(
                    ((GroupLayout) getContentPane().getLayout()).createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(20, 20, 20)
                        .addComponent(txtMateria, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(btnVolver)
                )
                .addComponent(jScrollPane1)
        );
           
           this.profesor = profesor;
           setLocationRelativeTo(null);
           configurarEventos();
           cargarTabla();
       }

        private void configurarEventos() {
            btnGuardar.addActionListener(e -> guardarNotas());
            btnVolver.addActionListener(e -> {
                this.dispose();
                new frmDocente(baseDatos,profesor).setVisible(true);
            });
        }

private void cargarTabla() {
    String materia = baseDatos.obtenerMateriaDocente(profesor);

    DefaultTableModel modelo = new DefaultTableModel(
        new Object[]{"Nombre", "Corte", "Nota"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column == 2; // Solo editable la columna de Nota
        }
    };

    String sql = "SELECT nombre, corte, nota FROM `" + materia + "`";
    System.out.println("📌 Materia del profesor: " + materia);
System.out.println("📌 Query ejecutada: SELECT nombre, corte, nota FROM `" + materia + "`");
    try (Connection conn = ConexionBD.getConnection();
         PreparedStatement stmt = conn.prepareStatement(sql);
         ResultSet rs = stmt.executeQuery()) {
        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getString("nombre"),
                rs.getInt("corte"),
                rs.getDouble("nota")
            });
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    tablaNotas.setModel(modelo);
    txtMateria.setText("Materia: " + materia.toUpperCase());
}


    
  private void guardarNotas() {
    String materia = baseDatos.obtenerMateriaDocente(profesor);

    DefaultTableModel modelo = (DefaultTableModel) tablaNotas.getModel();
    
    try (Connection conn = ConexionBD.getConnection()) {
     String sql = "UPDATE `" + materia + "` SET nota = ? WHERE nombre = ? AND corte = ?";

        PreparedStatement stmt = conn.prepareStatement(sql);

        for (int i = 0; i < modelo.getRowCount(); i++) {
            String nombre = modelo.getValueAt(i, 0).toString();
            int corte = (int) modelo.getValueAt(i, 1);
            double nota = Double.parseDouble(modelo.getValueAt(i, 2).toString());

            stmt.setDouble(1, nota);
            stmt.setString(2, nombre);
            stmt.setInt(3, corte);
            stmt.addBatch(); // Optimiza la inserción
        }
        stmt.executeBatch();
        JOptionPane.showMessageDialog(this, "✅ Notas guardadas correctamente");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ Error al guardar notas: " + e.getMessage());
        e.printStackTrace();
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNotas = new javax.swing.JTable();
        txtMateria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuardar.setText("guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnVolver.setText("volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        tablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaNotas);

        txtMateria.setText("materia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(txtMateria)
                .addGap(76, 76, 76)
                .addComponent(btnVolver))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnVolver)
                    .addComponent(txtMateria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaNotas;
    private javax.swing.JLabel txtMateria;
    // End of variables declaration//GEN-END:variables
}
