package vista;

import clases.ConexionBD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JiFrmPromedioGrupo extends javax.swing.JInternalFrame {

    private final String docente;
    private final String materia;

    public JiFrmPromedioGrupo(String docente, String materia) {
        initComponents();
        this.docente = docente;
        this.materia = materia;
        this.getContentPane().setBackground(new Color(214, 245, 255));
        cargarPromedios();
    }


    /**
     * Cargar los promedios por estudiante y el promedio general del grupo
     */
    private void cargarPromedios() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{"Estudiante", "Corte 1", "Corte 2", "Corte 3", "Promedio"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // tabla solo de lectura
            }
        };

        double sumaGeneral = 0;
        int cantidadEstudiantes = 0;

        // 🔹 Usamos el procedimiento almacenado
              String sql = "CALL listar_promedios_por_docente_materia(?, ?)";
    try (Connection conn = ConexionBD.getConnection();
         PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setString(1, docente);
        stmt.setString(2, materia);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                String estudiante = rs.getString("nombre") + " " + rs.getString("apellido");
                double c1 = rs.getDouble("corte1");
                double c2 = rs.getDouble("corte2");
                double c3 = rs.getDouble("corte3");

                double promedio = (c1 + c2 + c3) / 3.0;

                modelo.addRow(new Object[]{
                        estudiante,
                        String.format("%.2f", c1),
                        String.format("%.2f", c2),
                        String.format("%.2f", c3),
                        String.format("%.2f", promedio)
                });

                sumaGeneral += promedio;
                cantidadEstudiantes++;
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "❌ Error al cargar promedios: " + e.getMessage());
        }

        tablaNotas.setModel(modelo);

        if (cantidadEstudiantes > 0) {
            double promedioGrupo = sumaGeneral / cantidadEstudiantes;
            lbPromedio.setText(String.format("%.2f", promedioGrupo));
        } else {
            lbPromedio.setText("N/A");
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNotas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbPromedio = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        tablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaNotas);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("promedio del grupo:");

        lbPromedio.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbPromedio.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbPromedio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbPromedio))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbPromedio;
    private javax.swing.JTable tablaNotas;
    // End of variables declaration//GEN-END:variables
}
