/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import clases.Base_De_Datos;
import clases.ConexionBD;

import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author cymaniatico
 */
public class JiFrmPromedioGrupo extends javax.swing.JInternalFrame {
 
       
       private final Base_De_Datos baseDatos = new Base_De_Datos(); // 👈 Instancia de tu clase
       private final String docente;  // 👈 Nombre del docente logueado

    /**
     * Creates new form JiFrmPrueba
     */

    
  public JiFrmPromedioGrupo(String docente) {
        initComponents();
        this.docente = docente;
        this.getContentPane().setBackground(new Color(214, 245, 255));
        cargarPromedios();
    }

   
  private void cargarPromedios() {
    DefaultTableModel modelo = new DefaultTableModel(
        new Object[]{"Estudiante", "Promedio"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // 👈 Tabla de solo lectura
        }
    };

    double sumaGeneral = 0;
    int cantidadEstudiantes = 0;

    try (Connection conn = ConexionBD.getConnection()) {
        // 1. Usar el método de Base_De_Datos para obtener la materia del docente
        String materia = baseDatos.obtenerMateriaDocente(docente);

        if (materia == null) {
            System.out.println("⚠ El docente no tiene materia asignada.");
            tablaNotas.setModel(modelo);
            lbPromedio.setText("N/A");
            return;
        }

        // 2. Sacar promedios de cada estudiante en esa materia
        String sqlNotas = "SELECT nombre, AVG(nota) AS promedio " +
                          "FROM `" + materia + "` " +
                          "GROUP BY nombre";

        try (PreparedStatement stmt = conn.prepareStatement(sqlNotas);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                String estudiante = rs.getString("nombre");
                double promedio = rs.getDouble("promedio");

                modelo.addRow(new Object[]{
                    estudiante,
                    String.format("%.2f", promedio)
                });

                // 👇 acumular para promedio general
                sumaGeneral += promedio;
                cantidadEstudiantes++;
            }
        }

    } catch (Exception e) {
        e.printStackTrace();
    }

    tablaNotas.setModel(modelo);

    // 👇 Calcular promedio general del grupo
    if (cantidadEstudiantes > 0) {
        double promedioGrupo = sumaGeneral / cantidadEstudiantes;
        lbPromedio.setText(String.format("%.2f", promedioGrupo));
    } else {
        lbPromedio.setText("N/A");
    }
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNotas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbPromedio = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        tablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaNotas);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("promedio del grupo:");

        lbPromedio.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbPromedio.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbPromedio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbPromedio))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbPromedio;
    private javax.swing.JTable tablaNotas;
    // End of variables declaration//GEN-END:variables
}
