/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import clases.Base_De_Datos;
import clases.ConexionBD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.Box;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cymaniatico
 */
public class JiFrmPrueba extends javax.swing.JInternalFrame {
       private final Base_De_Datos baseDatos;
       private final String profesor;
    /**
     * Creates new form JiFrmPrueba
     */

    public JiFrmPrueba(Base_De_Datos basedatos, String profesor) {
        initComponents();
          this.baseDatos=basedatos;
          this.getContentPane().setBackground(new Color(255, 254, 214));
          this.profesor = profesor;
          cargarTabla();
        
    }
    
 private void cargarTabla() {
    String materia = baseDatos.obtenerMateriaDocente(profesor);
    jMenuBar1.add(Box.createHorizontalGlue()); 
    jMenuBar1.add(btnGuardar);

    // 🔹 Solo mostramos 2 columnas
    DefaultTableModel modelo = new DefaultTableModel(
        new Object[]{"Nombre", "Nota"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column == 1; // Solo editable la columna de Nota
        }
    };

    String sql = "SELECT nombre, nota FROM `" + materia + "`";
    try (Connection conn = ConexionBD.getConnection();
         PreparedStatement stmt = conn.prepareStatement(sql);
         ResultSet rs = stmt.executeQuery()) {

        while (rs.next()) {
            // Guardamos corte de forma "oculta" en un array paralelo
            modelo.addRow(new Object[]{
                rs.getString("nombre"),
                rs.getDouble("nota")
            });
            // Usamos setValueAt si queremos agregar corte como metadata
            // pero sin mostrarlo en la tabla
           
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    tablaNotas.setModel(modelo);
    lbMateria.setText("Materia: " + materia.toUpperCase());
}

 
    
    private void guardarNotas() {
    String materia = baseDatos.obtenerMateriaDocente(profesor);
    DefaultTableModel modelo = (DefaultTableModel) tablaNotas.getModel();

    try (Connection conn = ConexionBD.getConnection()) {
        String sqlUpdate = "UPDATE `" + materia + "` SET nota = ? WHERE nombre = ? AND corte = 1"; 
        // 👆 Si solo manejas 1 corte por ahora

        PreparedStatement stmt = conn.prepareStatement(sqlUpdate);

        for (int i = 0; i < modelo.getRowCount(); i++) {
            String nombre = modelo.getValueAt(i, 0).toString();
            double nota = Double.parseDouble(modelo.getValueAt(i, 1).toString());

            stmt.setDouble(1, nota);
            stmt.setString(2, nombre);
            stmt.addBatch();
        }

        stmt.executeBatch();
        JOptionPane.showMessageDialog(this, "✅ Notas guardadas correctamente");

        cargarTabla(); // 🔹 Refresca los datos
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ Error al guardar notas: " + e.getMessage());
        e.printStackTrace();
    }
}




    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNotas = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        lbMateria = new javax.swing.JMenu();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        tablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaNotas);

        btnGuardar.setText("guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lbMateria.setText("File");
        jMenuBar1.add(lbMateria);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        guardarNotas();
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu lbMateria;
    private javax.swing.JTable tablaNotas;
    // End of variables declaration//GEN-END:variables
}
