/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;




import clases.ConexionBD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author cymaniatico
 */
public class JiFrmQuitarMateria extends javax.swing.JInternalFrame {
 
       private final String alumno;
        
    /**
     * Creates new form JiFrmPrueba
     */

    public JiFrmQuitarMateria( String alumno) {
        initComponents();
        this.alumno = alumno;
        this.getContentPane().setBackground(new Color(214, 245, 255));
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombreMateria = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Nombre de la materia");

        jButton1.setText("quitar materia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreMateria))
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    String nombreMateria = txtNombreMateria.getText().trim();

    if (nombreMateria.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "⚠ Debes ingresar el nombre de la materia a quitar.",
                "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    try (Connection conn = ConexionBD.getConnection()) {
        conn.setAutoCommit(false); // Usamos transacción

        // 1. Buscar el docente asignado a la materia
        Integer idDocente = null;
        String sqlBuscar = "SELECT docente_id FROM Materias WHERE nombre_materia = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sqlBuscar)) {
            stmt.setString(1, nombreMateria);
            try (java.sql.ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    idDocente = rs.getInt("docente_id");
                    if (rs.wasNull()) {
                        idDocente = null; // si estaba NULL
                    }
                }
            }
        }

        if (idDocente == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "⚠ La materia no tiene un docente asignado o no existe.",
                    "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            conn.rollback();
            return;
        }

        // 2. Actualizar docente → dejarlo sin asignatura
        String sqlDocente = "UPDATE Docentes SET materia = 'sin asignatura' WHERE id = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sqlDocente)) {
            stmt.setInt(1, idDocente);
            stmt.executeUpdate();
        }

        // 3. Actualizar materia → dejarla libre y sin docente
        String sqlMateria = "UPDATE Materias SET docente_id = NULL, estado = 'libre' WHERE nombre_materia = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sqlMateria)) {
            stmt.setString(1, nombreMateria);
            stmt.executeUpdate();
        }

        conn.commit(); // Confirmamos la transacción

        javax.swing.JOptionPane.showMessageDialog(this,
                "✅ Materia liberada correctamente.\nEl docente quedó sin asignatura.",
                "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        txtNombreMateria.setText("");

    } catch (SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "❌ Error al liberar la materia: " + ex.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNombreMateria;
    // End of variables declaration//GEN-END:variables
}
