/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import clases.ConexionBD;

import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author cymaniatico
 */
public class JiFrmNotas extends javax.swing.JInternalFrame {
 
       private final String alumno;
    /**
     * Creates new form JiFrmPrueba
     */

    public JiFrmNotas( String alumno) {
        initComponents();
        this.alumno = alumno;
        this.getContentPane().setBackground(new Color(214, 245, 255));
        
        cargarNotas();
        
    }
    
 private void cargarNotas() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[]{"Materia", "Corte", "Nota"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // 🚫 Ninguna celda editable
            }
        };

        String[] materias = {"java", "poo", "materias_net"};

        double sumaNotas = 0;
        int cantidadNotas = 0;

        try (Connection conn = ConexionBD.getConnection()) {
            for (String mat : materias) {
                String sql = "SELECT corte, nota FROM `" + mat + "` WHERE nombre = ?";
                try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                    stmt.setString(1, alumno);
                    ResultSet rs = stmt.executeQuery();
                    while (rs.next()) {
                        double nota = rs.getDouble("nota");
                        sumaNotas += nota;
                        cantidadNotas++;

                        modelo.addRow(new Object[]{
                            mat.toUpperCase(),
                            rs.getInt("corte"),
                            nota
                        });
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        tablaNotas.setModel(modelo);

        // Calcular promedio
        if (cantidadNotas > 0) {
            double promedio = sumaNotas / cantidadNotas;
            lblPromedio.setText("Promedio general: " + String.format("%.2f", promedio));
        } else {
            lblPromedio.setText("Promedio general: N/A");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNotas = new javax.swing.JTable();
        lblPromedio = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        tablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaNotas);

        lblPromedio.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblPromedio.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPromedio)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JTable tablaNotas;
    // End of variables declaration//GEN-END:variables
}
