/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import clases.ConexionBD;

import clases.Base_De_Datos;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author cymaniatico
 */
public class JiFrmAsignarMaterias extends javax.swing.JInternalFrame {
 
  
        
    /**
     * Creates new form JiFrmPrueba
     */

    public JiFrmAsignarMaterias( String alumno,Base_De_Datos basedatos) {
        initComponents();
        this.getContentPane().setBackground(new Color(214, 245, 255));
        cargarDocentesDisponibles();  
        cargarMateriasDisponibles();
    }
    
    private void cargarDocentesDisponibles() {
        comboDocentes.removeAllItems();

        String sql = "SELECT id, nombre, apellido FROM Docentes WHERE materia = 'sin asignatura'";

        try (Connection conn = ConexionBD.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            boolean hayDocentes = false;
            while (rs.next()) {
                // Guarda ID oculto pero muestra nombre completo
                String docente = rs.getInt("id") + " - " +
                                 rs.getString("nombre") + " " +
                                 rs.getString("apellido");
                comboDocentes.addItem(docente);
                hayDocentes = true;
            }

            if (!hayDocentes) {
                comboDocentes.addItem("⚠ No hay docentes libres");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error cargando docentes: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarMateriasDisponibles() {
        comboMaterias.removeAllItems();

        String sql = "SELECT nombre_materia FROM Materias  where Materias.id_asignatura=\"x\";";

        try (Connection conn = ConexionBD.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            boolean hayMaterias = false;
            while (rs.next()) {
                String materia = rs.getString("nombre_materia");
                comboMaterias.addItem(materia);
                hayMaterias = true;
            }

            if (!hayMaterias) {
                comboMaterias.addItem("⚠ No hay materias disponibles");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error cargando materias: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboDocentes = new javax.swing.JComboBox<>();
        btnAsignar = new javax.swing.JButton();
        comboMaterias = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Materias disponibles");

        jLabel2.setText("asignar profesor ");

        comboDocentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAsignar.setText("asignar Docente");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        comboMaterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("id de la signatura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboMaterias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAsignar)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsignar)
                    .addComponent(comboMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        String materiaSeleccionada = (String) comboMaterias.getSelectedItem();
    String docenteSeleccionado = (String) comboDocentes.getSelectedItem();
    String idAsignatura = txtID.getText().trim();

    // Validaciones
    if (materiaSeleccionada == null || materiaSeleccionada.startsWith("⚠")) {
        JOptionPane.showMessageDialog(this,
                "⚠ Debes seleccionar una materia válida.",
                "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (docenteSeleccionado == null || docenteSeleccionado.startsWith("⚠")) {
        JOptionPane.showMessageDialog(this,
                "⚠ Debes seleccionar un docente válido.",
                "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (idAsignatura.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "⚠ Debes ingresar un ID de asignatura (campo vacío).",
                "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validar que el ID de asignatura sea solo una letra, ya que en BD es varchar(1)
    if (!idAsignatura.matches("[a-zA-Z]")) {
        JOptionPane.showMessageDialog(this,
                "⚠ El ID de asignatura debe ser una sola letra (ejemplo: A, B, C...).",
                "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try (Connection conn = ConexionBD.getConnection()) {
        conn.setAutoCommit(false);

        // Obtener el ID del docente desde el combo (formato: "id - Nombre Apellido")
        int idDocente = Integer.parseInt(docenteSeleccionado.split(" - ")[0]);

        // Obtener el ID de la materia según el nombre
        String sqlGetMateria = "SELECT nombre_materia FROM Materias WHERE nombre_materia = ? AND id_asignatura = 'x'";
        try (PreparedStatement stmt = conn.prepareStatement(sqlGetMateria)) {
            stmt.setString(1, materiaSeleccionada);
            ResultSet rs = stmt.executeQuery();
            if (!rs.next()) {
                throw new Exception("La materia seleccionada ya fue asignada o no existe.");
            }
        }

        // 1) Actualizar tabla MATERIAS con el ID del docente y el nuevo ID de asignatura
        String sqlUpdateMateria = "UPDATE Materias SET docente_id = ?, id_asignatura = ? WHERE nombre_materia = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sqlUpdateMateria)) {
            stmt.setInt(1, idDocente);
            stmt.setString(2, idAsignatura);
            stmt.setString(3, materiaSeleccionada);
            stmt.executeUpdate();
        }

        // 2) Actualizar tabla DOCENTES con nombre de materia y el id de asignatura
        String sqlUpdateDocente = "UPDATE Docentes SET materia = ?, id_materia = ? WHERE id = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sqlUpdateDocente)) {
            stmt.setString(1, materiaSeleccionada);
            stmt.setString(2, idAsignatura);
            stmt.setInt(3, idDocente);
            stmt.executeUpdate();
        }

        conn.commit();

        JOptionPane.showMessageDialog(this,
                "✅ Materia '" + materiaSeleccionada + "' asignada correctamente al docente.",
                "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Limpiar campos y recargar combos
        cargarDocentesDisponibles();
        cargarMateriasDisponibles();
        txtID.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "❌ Error al asignar la materia: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAsignarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JComboBox<String> comboDocentes;
    private javax.swing.JComboBox<String> comboMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
