/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import clases.Base_De_Datos;
import clases.ConexionBD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;



import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cymaniatico
 */
public class JiFrmListaestudiantes extends javax.swing.JInternalFrame {
       private final Base_De_Datos baseDatos;
       private final String profesor;
    /**
     * Creates new form JiFrmPrueba
     */

    public JiFrmListaestudiantes(Base_De_Datos basedatos, String profesor) {
        initComponents();
          this.baseDatos=basedatos;
          this.getContentPane().setBackground(new Color(255, 254, 214));
          this.profesor = profesor;
          cargarEstudiantes();
        
    }
    
    private void cargarEstudiantes() {
    // Modelo no editable
    DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // 🔒 ninguna celda editable
        }
    };

    // Definir columnas
    modelo.addColumn("CC");
    modelo.addColumn("Nombre");
    modelo.addColumn("Apellido");
    modelo.addColumn("Edad");
    modelo.addColumn("Teléfono");
    modelo.addColumn("Correo");

    // Asignar modelo a la tabla
    tablaEstudiantes.setModel(modelo);

    String sql = "SELECT a.cc, a.nombre, a.apellido, a.edad, a.telefono, a.correo\n" +
"        FROM Materias m\n" +
"        INNER JOIN Alumnos a ON m.alumno_id = a.id\n" +
"        INNER JOIN Docentes d ON m.docente_id = d.id\n" +
"        WHERE d.nombre = ? AND m.estado = 'activa';";

    try (Connection conn = baseDatos.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setString(1, profesor); // 👈 profesor que viene del constructor
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] fila = {
                rs.getString("cc"),
                rs.getString("nombre"),
                rs.getString("apellido"),
                rs.getString("edad"),
                rs.getString("telefono"),
                rs.getString("correo"),
            };
            modelo.addRow(fila);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,
            "Error cargando estudiantes: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
}



 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaEstudiantes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaEstudiantes;
    // End of variables declaration//GEN-END:variables
}
