/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.frm;

import vista.frm.frmLogin;
import vista.jifrm.JiFrmAsignarMaterias;
import vista.jifrm.JiFrmQuitarMateria;
import vista.jifrm.JiFrmCrearMateria;
import vista.jifrm.JiFrmRegistrar;
import vista.jifrm.JiFrmDatosEstudiandres;
import vista.jifrm.JiFrmDatosProfesores;
import clases.Base_De_Datos;
import clases.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.Box;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class frmAdministrador extends javax.swing.JFrame {
    private final Base_De_Datos baseDatos;
    private String nombre;
   

    /**
     * Creates new form frmAdministrador
     */
    public frmAdministrador(Base_De_Datos baseDatos,String nombreEstudiante) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.nombre=nombreEstudiante;
        btnnombre.setText("Bienvenido, " + nombreEstudiante);
        this.baseDatos = baseDatos;
        jMenuBar1.add(Box.createHorizontalGlue()); 
        jMenuBar1.add(btnVolver);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        jPanel = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnnombre = new javax.swing.JMenu();
        btngestionp = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        btncrearMateria = new javax.swing.JMenuItem();
        btnAsignarMateria = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnAlumnosDatos = new javax.swing.JMenuItem();
        btnDocentesDatos = new javax.swing.JMenuItem();
        btnReinicio = new javax.swing.JMenuItem();

        btnVolver.setText("cerrar seccion");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/hq720.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnnombre.setText("File");
        jMenuBar1.add(btnnombre);

        btngestionp.setText("gestionar ");
        btngestionp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem3.setText("registrar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        btngestionp.add(jMenuItem3);

        jMenu1.setText("Asignaturas");

        btncrearMateria.setText("crear materia");
        btncrearMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearMateriaActionPerformed(evt);
            }
        });
        jMenu1.add(btncrearMateria);

        btnAsignarMateria.setText("asignar materia");
        btnAsignarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarMateriaActionPerformed(evt);
            }
        });
        jMenu1.add(btnAsignarMateria);

        jMenuItem1.setText("Quitar Asignatura");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        btngestionp.add(jMenu1);

        jMenu2.setText("Datos");

        btnAlumnosDatos.setText("alumnos");
        btnAlumnosDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosDatosActionPerformed(evt);
            }
        });
        jMenu2.add(btnAlumnosDatos);

        btnDocentesDatos.setText("docentes");
        btnDocentesDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocentesDatosActionPerformed(evt);
            }
        });
        jMenu2.add(btnDocentesDatos);

        btngestionp.add(jMenu2);

        btnReinicio.setText("reiniciar periodo academico");
        btnReinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReinicioActionPerformed(evt);
            }
        });
        btngestionp.add(btnReinicio);

        jMenuBar1.add(btngestionp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        new frmLogin(baseDatos).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnReinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinicioActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "✅ semestre reiniciado");
        String sql = "call reiniciar_notas()";


        try (Connection conn = ConexionBD.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

                      stmt.executeUpdate();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "❌ Error al registrar estudiante: " + e.getMessage());
        }
    }//GEN-LAST:event_btnReinicioActionPerformed

    private void btncrearMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearMateriaActionPerformed
        // TODO add your handling code here:
        JiFrmCrearMateria Materia2=new JiFrmCrearMateria();
        jPanel.add(Materia2);
        Materia2.show();
    }//GEN-LAST:event_btncrearMateriaActionPerformed

    private void btnAsignarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarMateriaActionPerformed
        // TODO add your handling code here:
        JiFrmAsignarMaterias materia=new JiFrmAsignarMaterias(nombre, baseDatos);
        jPanel.add(materia);
        materia.show();
    }//GEN-LAST:event_btnAsignarMateriaActionPerformed

    private void btnAlumnosDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosDatosActionPerformed
        // TODO add your handling code here:
        JiFrmDatosEstudiandres LosNinos=new JiFrmDatosEstudiandres(baseDatos, nombre);
        jPanel.add(LosNinos);
        LosNinos.show();
    }//GEN-LAST:event_btnAlumnosDatosActionPerformed

    private void btnDocentesDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocentesDatosActionPerformed
        // TODO add your handling code here:
        JiFrmDatosProfesores Los_Hombre=new JiFrmDatosProfesores(baseDatos, nombre);
        jPanel.add(Los_Hombre);
        Los_Hombre.show();
                
    }//GEN-LAST:event_btnDocentesDatosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JiFrmQuitarMateria DELETE=new JiFrmQuitarMateria(nombre);
        jPanel.add(DELETE);
        DELETE.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JiFrmRegistrar registro=new JiFrmRegistrar();
        jPanel.add(registro);
        registro.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAlumnosDatos;
    private javax.swing.JMenuItem btnAsignarMateria;
    private javax.swing.JMenuItem btnDocentesDatos;
    private javax.swing.JMenuItem btnReinicio;
    private javax.swing.JButton btnVolver;
    private javax.swing.JMenuItem btncrearMateria;
    private javax.swing.JMenu btngestionp;
    private javax.swing.JMenu btnnombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JDesktopPane jPanel;
    // End of variables declaration//GEN-END:variables

   
}
