package Vista.frm.Panel;

import Clases.Base_De_Datos;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.util.regex.Pattern;
import java.util.List;

public class PanelRegistroPersona extends JPanel {

    private final Base_De_Datos baseDatos;

    private final JTextField txtNombre = new JTextField(15);
    private final JTextField txtSegundoNombre = new JTextField(15);
    private final JTextField txtApellido = new JTextField(15);
    private final JTextField txtSegundoApellido = new JTextField(15);
    private final JTextField txtEdad = new JTextField(5);
    private final JTextField txtTelefono = new JTextField(15);
    private final JTextField txtCorreo = new JTextField(20);
    private final JTextField txtDireccion = new JTextField(25);
    private final JTextField txtCedula = new JTextField(15);
    private final JComboBox<String> cmbGenero = new JComboBox<>(new String[]{"Masculino", "Femenino", "Otro"});
    private final JComboBox<String> cmbCargo = new JComboBox<>();
    private final JComboBox<String> cmbCarrera = new JComboBox<>();

    private final JButton btnRegistrar = new JButton("Registrar persona");
    private final JButton btnLimpiar = new JButton("Limpiar");

    private static final Pattern LETRAS = Pattern.compile("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$");
    private static final Pattern CORREO = Pattern.compile("^[\\w._%+-]+@(gmail|hotmail|outlook|yahoo|unal|utp|poli)\\.com$", Pattern.CASE_INSENSITIVE);
    private static final Pattern NUMEROS = Pattern.compile("^\\d+$");
    private static final Pattern TELEFONO = Pattern.compile("^\\d{7,15}$");

    public PanelRegistroPersona(Base_De_Datos baseDatos) {
        this.baseDatos = baseDatos;
        setBackground(new Color(245, 245, 245));
        setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(new Color(70, 130, 180), 2),
                "Registro de Persona",
                TitledBorder.CENTER,
                TitledBorder.TOP,
                new Font("Arial", Font.BOLD, 18),
                new Color(70, 130, 180)
        ));
        initComponentes();
        cargarCargos();
        cargarCarreras();
        ajustarPorCargo();
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

      private void initComponentes() {
        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;

        Font labelFont = new Font("Arial", Font.BOLD, 14);
        Font fieldFont = new Font("Arial", Font.PLAIN, 14);

        // Fila 0
        gbc.gridx = 0; gbc.gridy = 0;
        add(createLabel("Primer nombre:", labelFont), gbc);
        gbc.gridx = 1;
        add(txtNombre, gbc);
        gbc.gridx = 2;
        add(createLabel("Segundo nombre:", labelFont), gbc);
        gbc.gridx = 3;
        add(txtSegundoNombre, gbc);

        // Fila 1
        gbc.gridx = 0; gbc.gridy = 1;
        add(createLabel("Primer apellido:", labelFont), gbc);
        gbc.gridx = 1;
        add(txtApellido, gbc);
        gbc.gridx = 2;
        add(createLabel("Segundo apellido:", labelFont), gbc);
        gbc.gridx = 3;
        add(txtSegundoApellido, gbc);

        // Fila 2
        gbc.gridx = 0; gbc.gridy = 2;
        add(createLabel("Edad:", labelFont), gbc);
        gbc.gridx = 1;
        add(txtEdad, gbc);
        gbc.gridx = 2;
        add(createLabel("Género:", labelFont), gbc);
        gbc.gridx = 3;
        add(cmbGenero, gbc);

        // Fila 3
        gbc.gridx = 0; gbc.gridy = 3;
        add(createLabel("Cédula:", labelFont), gbc);
        gbc.gridx = 1;
        add(txtCedula, gbc);
        gbc.gridx = 2;
        add(createLabel("Teléfono:", labelFont), gbc);
        gbc.gridx = 3;
        add(txtTelefono, gbc);

        // Fila 4
        gbc.gridx = 0; gbc.gridy = 4;
        add(createLabel("Correo:", labelFont), gbc);
        gbc.gridx = 1;
        add(txtCorreo, gbc);
        gbc.gridx = 2;
        add(createLabel("Dirección:", labelFont), gbc);
        gbc.gridx = 3;
        add(txtDireccion, gbc);

        // Fila 5
        gbc.gridx = 0; gbc.gridy = 5;
        add(createLabel("Cargo:", labelFont), gbc);
        gbc.gridx = 1;
        add(cmbCargo, gbc);
        gbc.gridx = 2;
        add(createLabel("Carrera (solo alumno):", labelFont), gbc);
        gbc.gridx = 3;
        add(cmbCarrera, gbc);

        // Fila 6
        gbc.gridx = 1; gbc.gridy = 6;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.CENTER;
        JPanel btnPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 0));
        btnPanel.setOpaque(false);
        btnPanel.add(btnRegistrar);
        btnPanel.add(btnLimpiar);
        add(btnPanel, gbc);

        // Listeners
        cmbCargo.addActionListener(e -> ajustarPorCargo());
        btnRegistrar.addActionListener(e -> registrarPersona());
        btnLimpiar.addActionListener(e -> limpiarCampos());

        // Estilo botones
        styleButton(btnRegistrar, new Color(34, 139, 34));
        styleButton(btnLimpiar, new Color(220, 20, 60));
    }

    private JLabel createLabel(String text, Font font) {
        JLabel label = new JLabel(text);
        label.setFont(font);
        label.setForeground(new Color(70, 70, 70));
        return label;
    }

    private void styleButton(JButton button, Color color) {
        button.setFont(new Font("Arial", Font.BOLD, 14));
        button.setBackground(color);
        button.setForeground(Color.WHITE);
        button.setFocusPainted(false);
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    private void cargarCargos() {
        cmbCargo.removeAllItems();
        String[] cargosPermitidos = {
            "alumno",
            "docente",
            "administrador",
            "registro y control"
        };
        for (String cargo : cargosPermitidos) {
            cmbCargo.addItem(cargo);
        }
    }

    private void cargarCarreras() {
        cmbCarrera.removeAllItems();
        
        try {
            List<String> carreras = baseDatos.cargarCarrerasRegistro();
            
            if (carreras.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se pudieron cargar las carreras o no hay carreras registradas.");
            } else {
                for (String carrera : carreras) {
                    cmbCarrera.addItem(carrera);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar carreras: " + ex.getMessage());
        }
    }


    private void ajustarPorCargo() {
        boolean esAlumno = "alumno".equalsIgnoreCase((String) cmbCargo.getSelectedItem());
        cmbCarrera.setVisible(esAlumno);
    }

    private boolean validarCampos() {
        // Validar nombre (obligatorio)
        String nombre = txtNombre.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El primer nombre es obligatorio.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
            return false;
        }
        if (!LETRAS.matcher(nombre).matches()) {
            JOptionPane.showMessageDialog(this, "El nombre solo debe contener letras.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
            return false;
        }

        // Validar segundo nombre (opcional)
        String segundoNombre = txtSegundoNombre.getText().trim();
        if (!segundoNombre.isEmpty() && !LETRAS.matcher(segundoNombre).matches()) {
            JOptionPane.showMessageDialog(this, "El segundo nombre solo debe contener letras.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            txtSegundoNombre.requestFocus();
            return false;
        }

        // Validar apellido (obligatorio)
        String apellido = txtApellido.getText().trim();
        if (apellido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El primer apellido es obligatorio.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            txtApellido.requestFocus();
            return false;
        }
        if (!LETRAS.matcher(apellido).matches()) {
            JOptionPane.showMessageDialog(this, "El apellido solo debe contener letras.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            txtApellido.requestFocus();
            return false;
        }

        // Validar segundo apellido (opcional)
        String segundoApellido = txtSegundoApellido.getText().trim();
        if (!segundoApellido.isEmpty() && !LETRAS.matcher(segundoApellido).matches()) {
            JOptionPane.showMessageDialog(this, "El segundo apellido solo debe contener letras.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            txtSegundoApellido.requestFocus();
            return false;
        }

        // Validar edad (obligatorio)
        String edadStr = txtEdad.getText().trim();
        if (edadStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La edad es obligatoria.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            txtEdad.requestFocus();
            return false;
        }
        if (!NUMEROS.matcher(edadStr).matches()) {
            JOptionPane.showMessageDialog(this, "La edad debe ser un número válido.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            txtEdad.requestFocus();
            return false;
        }
        int edad = Integer.parseInt(edadStr);
        if (edad < 12 || edad > 100) {
            JOptionPane.showMessageDialog(this, "La edad debe estar entre 12 y 100 años.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            txtEdad.requestFocus();
            return false;
        }

        // Validar cédula (obligatorio)
        String cedula = txtCedula.getText().trim();
        if (cedula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La cédula es obligatoria.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            txtCedula.requestFocus();
            return false;
        }
        if (!cedula.matches("\\d{6,10}")) {
            JOptionPane.showMessageDialog(this, "Cédula inválida: debe contener 6-10 dígitos numéricos.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            txtCedula.requestFocus();
            return false;
        }

        // Validar teléfono (opcional pero si se ingresa debe ser numérico)
        String telefono = txtTelefono.getText().trim();
        if (!telefono.isEmpty() && !TELEFONO.matcher(telefono).matches()) {
            JOptionPane.showMessageDialog(this, "Teléfono inválido: debe contener entre 7 y 15 dígitos.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            txtTelefono.requestFocus();
            return false;
        }

        // Validar correo (obligatorio)
        String correo = txtCorreo.getText().trim();
        if (correo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El correo es obligatorio.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            txtCorreo.requestFocus();
            return false;
        }
        if (!CORREO.matcher(correo).matches()) {
            JOptionPane.showMessageDialog(this, "El correo debe ser válido (ej: nombre@dominio.com).", "Error de validación", JOptionPane.ERROR_MESSAGE);
            txtCorreo.requestFocus();
            return false;
        }

        // Validar dirección (opcional)
        String direccion = txtDireccion.getText().trim();
        if (direccion.length() > 100) {
            JOptionPane.showMessageDialog(this, "La dirección no puede exceder los 100 caracteres.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            txtDireccion.requestFocus();
            return false;
        }

        // Validar que se haya seleccionado carrera si el cargo es alumno
        String cargo = ((String) cmbCargo.getSelectedItem()).toLowerCase();
        if ("alumno".equals(cargo) && cmbCarrera.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una carrera para el alumno.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            cmbCarrera.requestFocus();
            return false;
        }

        return true;
    }
    
    
     

   
    
    private void registrarPersona() {
        // VALIDACIÓN PRINCIPAL CORREGIDA: Si la validación falla, NO continúa
        if (!validarCampos()) {
            return; // Detener el registro si hay errores de validación
        }

        try {
            String nom = txtNombre.getText().trim();
            String segNom = txtSegundoNombre.getText().trim();
            String ape = txtApellido.getText().trim();
            String segApe = txtSegundoApellido.getText().trim();
            int edad = Integer.parseInt(txtEdad.getText().trim());
            String tel = txtTelefono.getText().trim();
            String mail = txtCorreo.getText().trim();
            String dir = txtDireccion.getText().trim();
            String ced = txtCedula.getText().trim();
            String gen = (String) cmbGenero.getSelectedItem();
            String cargo = ((String) cmbCargo.getSelectedItem()).toLowerCase();
            String carrera = cmbCarrera.isVisible() ? (String) cmbCarrera.getSelectedItem() : null;

            boolean exito = baseDatos.registrarPersonal(
                nom, segNom, ape, segApe, edad, tel, mail, dir, ced, gen, cargo, carrera
            );

            if (exito) {
                JOptionPane.showMessageDialog(this, "✅ Persona registrada exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "❌ Error al registrar la persona. El usuario ya puede existir.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "❌ Error inesperado: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
  
    
    
    private void limpiarCampos() {
        txtNombre.setText("");
        txtSegundoNombre.setText("");
        txtApellido.setText("");
        txtSegundoApellido.setText("");
        txtEdad.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        txtCedula.setText("");
        cmbGenero.setSelectedIndex(0);
        cmbCargo.setSelectedIndex(0);
        if (cmbCarrera.getItemCount() > 0) {
            cmbCarrera.setSelectedIndex(0);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
