/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.frm.Panel;

import Clases.ConexionBD;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class PanelCrearCarreraConMaterias extends JPanel {

      private JTextField txtNombreCarrera = new JTextField(20);
    private JButton btnCrear = new JButton("Crear carrera con materias seleccionadas");
    private JPanel panelMaterias = new JPanel(new GridLayout(0, 3, 5, 5)); // 3 columnas
    private List<JCheckBox> checkBoxes = new ArrayList<>();

    public PanelCrearCarreraConMaterias() {
        setLayout(new BorderLayout(10, 10));
        setBorder(BorderFactory.createTitledBorder("Crear carrera y asignar materias"));

        add(crearPanelNombre(), BorderLayout.NORTH);
        add(new JScrollPane(panelMaterias), BorderLayout.CENTER);
        add(crearPanelBoton(), BorderLayout.SOUTH);

        cargarTodasLasMaterias(); // ✅ solo materias "libres"
    }


    private JPanel crearPanelNombre() {
        JPanel p = new JPanel(new FlowLayout(FlowLayout.LEFT));
        p.add(new JLabel("Nombre de la carrera:"));
        p.add(txtNombreCarrera);
        return p;
    }

    private JPanel crearPanelBoton() {
        JPanel p = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        p.add(btnCrear);
        btnCrear.addActionListener(e -> crearCarreraConMaterias());
        return p;
    }

    private void cargarTodasLasMaterias() {
    checkBoxes.clear();
    panelMaterias.removeAll();

    // ✅ Trae TODAS las materias (de cualquier carrera)
    String sql = "SELECT DISTINCT nombre FROM Materias ORDER BY nombre";
    try (Connection conn = ConexionBD.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {
        while (rs.next()) {
            JCheckBox cb = new JCheckBox(rs.getString("nombre"));
            checkBoxes.add(cb);
            panelMaterias.add(cb);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al cargar materias: " + ex.getMessage());
    }
    panelMaterias.revalidate();
    panelMaterias.repaint();
}

   private void crearCarreraConMaterias() {
        String nombreCarrera = txtNombreCarrera.getText().trim();
        if (nombreCarrera.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escribe un nombre para la carrera");
            return;
        }

        List<String> seleccionadas = new ArrayList<>();
        for (JCheckBox cb : checkBoxes) {
            if (cb.isSelected()) seleccionadas.add(cb.getText());
        }

        if (seleccionadas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona al menos una materia");
            return;
        }

        String sql = "CALL crear_carrera_con_materias(?, ?)";
        try (Connection conn = ConexionBD.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, nombreCarrera);
            ps.setString(2, String.join(",", seleccionadas));
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "✅ Carrera creada y materias asignadas");
            txtNombreCarrera.setText("");
            cargarTodasLasMaterias();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
