package Vista.frm.Panel;

import Clases.Base_De_Datos;  
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

public class PanelCrearCarreraConMaterias extends JPanel {

    private JTextField txtNombreCarrera = new JTextField(20);
    private JButton btnCrear = new JButton("Crear carrera con materias seleccionadas");
    private JPanel panelMaterias = new JPanel(new GridLayout(0, 3, 5, 5));
    private List<JCheckBox> checkBoxes = new ArrayList<>();
    private Base_De_Datos basedatos = new Base_De_Datos();  

    public PanelCrearCarreraConMaterias() {
        setLayout(new BorderLayout(10, 10));
        setBorder(BorderFactory.createTitledBorder("Crear carrera y asignar materias"));

        add(crearPanelNombre(), BorderLayout.NORTH);
        add(new JScrollPane(panelMaterias), BorderLayout.CENTER);
        add(crearPanelBoton(), BorderLayout.SOUTH);

        cargarTodasLasMaterias();
    }

    private JPanel crearPanelNombre() {
        JPanel p = new JPanel(new FlowLayout(FlowLayout.LEFT));
        p.add(new JLabel("Nombre de la carrera:"));
        p.add(txtNombreCarrera);
        return p;
    }

    private JPanel crearPanelBoton() {
        JPanel p = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        p.add(btnCrear);
        btnCrear.addActionListener(e -> crearCarreraConMaterias());
        return p;
    }

    private void cargarTodasLasMaterias() {
        checkBoxes.clear();
        panelMaterias.removeAll();

        try {
            List<String> materias = basedatos.listarTodasLasMaterias();
            for (String materia : materias) {
                JCheckBox cb = new JCheckBox(materia);
                checkBoxes.add(cb);
                panelMaterias.add(cb);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar materias: " + ex.getMessage());
        }
        
        panelMaterias.revalidate();
        panelMaterias.repaint();
    }

    private void crearCarreraConMaterias() {
        String nombreCarrera = txtNombreCarrera.getText().trim();
        if (nombreCarrera.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escribe un nombre para la carrera");
            return;
        }

        List<String> seleccionadas = new ArrayList<>();
        for (JCheckBox cb : checkBoxes) {
            if (cb.isSelected()) seleccionadas.add(cb.getText());
        }

        if (seleccionadas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona al menos una materia");
            return;
        }

        try {
            basedatos.crearCarreraConMaterias(nombreCarrera, seleccionadas);
            JOptionPane.showMessageDialog(this, "✅ Carrera creada y materias asignadas");
            txtNombreCarrera.setText("");
            cargarTodasLasMaterias();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
